trigger: none

schedules:
- cron: "0 8-12 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: serverless

jobs:

- job: build
  timeoutInMinutes: 50

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: |
      pip install azure-cli
      az extension add --name azure-devops
    displayName: 'Install azure-cli'

  - script: |
      python3 main.py --client az --username $AZ_USERNAME --password $AZ_PASSWORD
    displayName: 'Run'
