name: Serverless

on:
  push:
    branches: [ master ]
#  schedule:
#    - cron: '55 4 * * *'

env:
  project: ${{ secrets.PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: requirements
        run: |
          pip3 install -r requirements.txt
          pip3 install azure-cli
          az extension add --name azure-devops

      - name: Run appletuan
        run: |
          python3 main.py --client huawei --username ${{ secrets.HW_USERNAME }} --password ${{ secrets.HW_USERNAME }}