name: Uptime

on:
#  push:
#    branches: [ master ]
  schedule:
    - cron: '0 */2 * * *'

env:
  db_key: ${{ secrets.DB_KEY }}
  db_user: ${{ secrets.DB_USER }}
  tg_bot: ${{ secrets.TG_BOT }}
  tg_chat_id: ${{ secrets.TG_CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run t66y
      run: |
        python3 main.py --client uptime